[tool.poetry]
name = "kpi-tasks"
version = "0.1.0"
description = "Tasks from KPI"
authors = ["VAlduinV"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
polars = "^0.19.3"
xlsx2csv = "^0.8.1"
pandas = "*"
openpyxl = "^3.1.2"
requests = "^2.31.0"
matplotlib = "^3.8.0"
lxml = "^4.9.3"
html5lib = "^1.1"
beautifulsoup4 = "^4.12.2"
mplcyberpunk = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
